// AUTO-GENERATED by tool/gen_stdlib.dart — do not edit manually.
// Run: dart tool/gen_stdlib.dart

/// Embedded standard library sources, keyed by module path.
/// Excludes '*_test.mpd' files.
/// Sub-directory modules use '.' as separator: 'hosted.memory'.
const Map<String, String> kStdlib = {
  'console': """// ── transport ────────────────────────────────────────────────────────────────
//
// write_byte dispatches through a function pointer.
// Default: HOSTED/MCU32 → putchar wrapper.  Other MCU → NULL (call console::init(fn) before use).
// Override at runtime: console::init(fn) for custom transports (UART, USB, mock tests).
import string::format

#if HOSTED || MCU32
@raw("#include <stdio.h>")

@extern("putchar({b})")
fun _putchar(b: byte)

fun _write_byte_default(b: byte)
    _putchar(b)

var _write_byte: fun(byte) = _write_byte_default
#else
var _write_byte: fun(byte)
#end

fun init(write_byte: fun(byte))
    _write_byte = write_byte

@inline
fun write_byte(b: byte)
    _write_byte(b)

// ── primitives ───────────────────────────────────────────────────────────────

fun print(string: byte[])
    write_string(string)
    write_byte(10)

fun print_args(string: byte[], args: int[])
    var buf: byte[128]
    print(format(string, buf, args))

fun write_string(string: byte[])
    for i in 0..string.size()
        write_byte(string[i])

fun write_bool(value: bool)
    if value
        write_byte('t')
        write_byte('r')
        write_byte('u')
        write_byte('e')
    else
        write_byte('f')
        write_byte('a')
        write_byte('l')
        write_byte('s')
        write_byte('e')

// ── unsigned integers ─────────────────────────────────────────────────────────

fun write_u64(value: u64)
    var buf: byte[20]
    var i: int = 19
    if value == 0
        write_byte('0')
        return
    while value > 0
        buf[i] = byte(value % 10 + 48)
        value = value / 10
        i -= 1
    for  j in (i + 1)..20
        write_byte(buf[j])

fun write_u32(value: u32)
    write_u64(u64(value))

fun write_u16(value: u16)
    write_u64(u64(value))

fun write_u8(value: u8)
    write_u64(u64(value))

// ── signed integers ───────────────────────────────────────────────────────────

fun write_i64(value: i64)
    if value < 0
        write_byte('-')
        write_u64(u64(i64(0) - value))
    else
        write_u64(u64(value))

fun write_i32(value: i32)
    write_i64(i64(value))

fun write_i16(value: i16)
    write_i64(i64(value))

fun write_i8(value: i8)
    write_i64(i64(value))

fun write_int(value: int)
    write_i64(i64(value))

// ── float ─────────────────────────────────────────────────────────────────────
//
// Naive float write: separates integer and fractional parts, extracts decimal
// digits by successive * 10. Accurate to ~6 significant digits (float precision).
// Does not handle NaN or Inf.

fun write_float(value: float)
    var abs: float = value
    if value < 0.0
        write_byte('-')
        abs = 0.0 - value
    val int_part := int(abs)
    write_int(int_part)
    write_byte('.')
    var frac: float = abs - float(int_part)
    for i in 0..4
        frac = frac * 10.0
        val digit := int(frac)
        write_byte(byte(digit + 48))
        frac = frac - float(digit)

// ── Q16 (16.16 fixed-point) ───────────────────────────────────────────────────
//
// 16.16 fixed-point: high 16 bits = integer part, low 16 bits = fractional part.
// e.g. write_q16(0x00018000) → "1.5000"   (1 + 32768/65536)
//      write_q16(0xFFFE8000) → "-1.5000"

fun write_q16(value: q16)
    var abs: u32 = 0
    if value < 0
        write_byte('-')
        abs = u32(0 - value)
    else
        abs = u32(value)

    // integer part: high 16 bits
    write_u32(abs >> 16)

    write_byte('.')
    // fractional part: low 16 bits
    // extract each decimal digit: multiply frac by 10, digit = high 16 bits
    var frac: u32 = abs & 0xFFFF
    for i in 0..4
        frac *= 10
        write_byte(byte((frac >> 16) + 48))
        frac = frac & 0xFFFF

fun write_fixed(value: fixed)
    write_q16(q16(value))
""",
  'hosted.allocator': """#if HOSTED

@raw("#include <stdlib.h>")

@extern("malloc")
fun _malloc(size: int): &byte

@extern("realloc")
fun _realloc(pointer: &byte, new_size: int): &byte

@extern("free")
fun _free(pointer: &byte)

// Heap allocator for growable containers (HOSTED only).
// Wraps malloc/realloc/free. Has no state — store a pointer to share ownership.
class HeapAllocator()
    var _pad: byte = 0    // keeps struct non-empty

    fun allocate_array<T>(len: int): T[]
        val size := sizeof<T>() * len
        val pointer := &T(_malloc(size))
        return {pointer, len}

    fun realloc_array<T>(array: T[], new_length: int): T[]
        val size := sizeof<T>() * new_length
        val pointer := &T(_realloc(&byte(array.ptr), size))
        return {pointer, new_length}

    fun free_array<T>(array: T[])
        _free(&byte(array.ptr))

#end
""",
  'hosted.args': """#if HOSTED

// Access to C main() argc / argv.
// argc() returns argument count (includes program name at index 0).
// argv(i) returns argument i as a byte[] slice.

@raw("#include <string.h>")

@extern("__mp_argc")
fun arg_count(): int

@extern("((uint8_t*)__mp_argv[{i}])")
fun _arg_pointer(i: int): &byte

@extern("(uint32_t)strlen(__mp_argv[{i}])")
fun _arg_len(i: int): u32

fun arg_value(i: int) byte[]
    return {_arg_pointer(i), _arg_len(i)}

#end
""",
  'hosted.collection': """#if HOSTED
import hosted.allocator::HeapAllocator

class HeapList<T>()
    var _buffer: T[]
    var _size: int = 0
    var _heap: &HeapAllocator

    fun init(heap: &HeapAllocator)
        _heap = heap
        _buffer = heap.allocate_array<T>(8)

    @inline
    fun push(value: T) bool
        if _size >= _buffer.size()
            _buffer = _heap.realloc_array<T>(_buffer, _buffer.size() * 2)
            if _buffer.size() == 0
                return false
        _buffer[_size] = value
        _size += 1
        return true

    @inline
    fun pop() bool
        if _size == 0
            return false
        _size -= 1
        return true

    fun insert(i: int, value: T) bool
        if i > _size
            return false
        if _size >= _buffer.size()
            _buffer = _heap.realloc_array<T>(_buffer, _buffer.size() * 2)
            if _buffer.size() == 0
                return false
        var j: int = _size
        while j > i
            _buffer[j] = _buffer[j - 1]
            j -= 1
        _buffer[i] = value
        _size += 1
        return true

    @inline
    fun get(i: int) T
        return _buffer[i]

    @inline
    fun set(i: int, value: T)
        _buffer[i] = value

    @inline
    fun top() T
        return _buffer[_size - 1]

    @inline
    fun size() int
        return _size

    @inline
    fun capacity() int
        return _buffer.size()

    @inline
    fun is_empty() bool
        return _size == 0

    @inline
    fun clear()
        _size = 0

    fun free()
        _heap.free_array<T>(_buffer)
        _buffer = {null, 0}
        _size = 0

// ── HeapMap ───────────────────────────────────────────────────────────────────
// Hash map with string (byte[]) keys and generic values. HOSTED only.
// Uses FNV-1a hashing, linear probing, 75% load-factor resize.
// Keys are copied into an owned flat byte pool — keys need not outlive the map.

class HeapMap<T>()
    var _key_start: int[]   // offset into _pool per slot
    var _key_len: int[]     // key length per slot
    var _pool: byte[]         // flat owned key byte storage
    var _pool_used: int = 0
    var _values: T[]
    var _state: byte[]        // 0=empty 1=used 2=deleted
    var _size: int = 0
    var _capacity: int = 0
    var _heap: &HeapAllocator

    fun init(heap: &HeapAllocator)
        _heap = heap
        _capacity = 8
        _key_start = heap.allocate_array<int>(int(_capacity))
        _key_len = heap.allocate_array<int>(int(_capacity))
        _pool = heap.allocate_array<byte>(128)
        _values = heap.allocate_array<T>(int(_capacity))
        _state = heap.allocate_array<byte>(int(_capacity))
        for i in 0.._capacity
            _state[i] = 0

    fun _hash(key: byte[]): u32
        var h: u32 = 2166136261
        for i in 0..key.size()
            h = h ^ u32(key[i])
            h = h * 16777619
        return h % _capacity

    fun _key_eq(slot: u32, key: byte[]): bool
        if _key_len[slot] != key.size()
            return false
        val start := _key_start[slot]
        for i in 0..key.size()
            if _pool[start + i] != key[i]
                return false
        return true

    // Returns slot for key (existing) or first available slot (empty/tombstone).
    // Returns _capacity if the table is completely full with no match.
    fun _find_slot(key: byte[]): u32
        var slot := _hash(key)
        var first_del: u32 = _capacity
        for i in 0.._capacity
            if _state[slot] == 0
                if first_del != _capacity
                    return first_del
                return slot
            if _state[slot] == 2
                if first_del == _capacity
                    first_del = slot
            else
                if _key_eq(slot, key)
                    return slot
            slot = (slot + 1) % _capacity
            i += 1
        if first_del != _capacity
            return first_del
        return _capacity

    fun contains(key: byte[]): bool
        if _capacity == 0
            return false
        val slot := _find_slot(key)
        if slot >= _capacity
            return false
        return _state[slot] == 1

    // Returns value. Caller must check contains() first; behaviour is
    // undefined when the key is absent.
    fun get(key: byte[]): T
        val slot := _find_slot(key)
        return _values[slot]

    fun set(key: byte[], value: T)
        if _size * 4 >= int(_capacity) * 3
            _grow()
        val slot := _find_slot(key)
        if slot >= _capacity
            return
        if _state[slot] != 1
            _pool_ensure(key.size())
            val start := _pool_used
            var i: int = 0
            while i < key.size()
                _pool[start + i] = key[i]
                i += 1
            _pool_used += key.size()
            _key_start[slot] = start
            _key_len[slot] = key.size()
            _state[slot] = 1
            _size += 1
        _values[slot] = value

    fun remove(key: byte[]): bool
        if _capacity == 0
            return false
        val slot := _find_slot(key)
        if slot >= _capacity
            return false
        if _state[slot] != 1
            return false
        _state[slot] = 2
        _size -= 1
        return true

    fun size(): int
        return _size

    fun _pool_ensure(needed: int)
        if _pool_used + needed <= _pool.size()
            return
        var new_size := _pool.size() * 2
        if new_size < _pool_used + needed
            new_size = _pool_used + needed
        _pool = _heap.realloc_array<byte>(_pool, new_size)

    fun _grow()
        val old_key_start := _key_start
        val old_key_len := _key_len
        val old_pool := _pool
        val old_values := _values
        val old_state := _state
        val old_cap := _capacity
        _capacity = old_cap * 2
        _key_start = _heap.allocate_array<int>(int(_capacity))
        _key_len = _heap.allocate_array<int>(int(_capacity))
        _pool = _heap.allocate_array<byte>(_pool_used + 64)
        _pool_used = 0
        _values = _heap.allocate_array<T>(int(_capacity))
        _state = _heap.allocate_array<byte>(int(_capacity))
        _size = 0
        for i in 0.._capacity
            _state[i] = 0
        for i in 0..old_cap
            if old_state[i] == 1
                val s := old_key_start[i]
                val l := old_key_len[i]
                val key := {&old_pool[s], l}
                set(key, old_values[i])
        _heap.free_array<int>(old_key_start)
        _heap.free_array<int>(old_key_len)
        _heap.free_array<byte>(old_pool)
        _heap.free_array<T>(old_values)
        _heap.free_array<byte>(old_state)

    fun free()
        _heap.free_array<int>(_key_start)
        _heap.free_array<int>(_key_len)
        _heap.free_array<byte>(_pool)
        _heap.free_array<T>(_values)
        _heap.free_array<byte>(_state)
        _key_start = {null, 0}
        _key_len = {null, 0}
        _pool = {null, 0}
        _values = {null, 0}
        _state = {null, 0}
        _size = 0
        _capacity = 0

#end
""",
  'hosted.file': """#if HOSTED
@raw("#include <stdio.h>")

@extern("fopen((const char*){path}.ptr, (const char*){mode}.ptr)")
fun _fopen(path: byte[], mode: byte[]): &void

@extern("fclose((FILE*){handle})")
fun _fclose(handle: &void)

@extern("(int32_t)fread({buf}.ptr, 1, {buf}.size, (FILE*){handle})")
fun _fread(buf: byte[], handle: &void): int

@extern("(int32_t)fwrite({buf}.ptr, 1, {buf}.size, (FILE*){handle})")
fun _fwrite(buf: byte[], handle: &void): int

@extern("(fgets((char*){buf}.ptr, (int){buf}.size, (FILE*){handle}) != NULL)")
fun _fgets(buf: byte[], handle: &void): bool

@extern("fflush((FILE*){handle})")
fun _fflush(handle: &void)

@extern("fseek((FILE*){handle}, (long){pos}, 0)")
fun _fseek(handle: &void, pos: int)

@extern("(int32_t)ftell((FILE*){handle})")
fun _ftell(handle: &void): int

@extern("(({handle}) != NULL)")
fun _ptr_valid(handle: &void): bool

const READ        = "r"
const WRITE       = "w"
const APPEND      = "a"
const READ_WRITE  = "r+"
const WRITE_READ  = "w+"
const APPEND_READ = "a+"

class File()
    var _handle: &void
    var _open: bool

    fun open(path: byte[], mode: byte[]): bool
        _handle = _fopen(path, mode)
        _open = _ptr_valid(_handle)
        return _open

    fun close()
        if _open
            _fclose(_handle)
            _open = false

    @inline
    fun is_open(): bool
        return _open

    fun read_bytes(buf: byte[]): int
        return _fread(buf, _handle)

    fun write_bytes(buf: byte[]): int
        return _fwrite(buf, _handle)

    @inline
    fun write_string(string: byte[])
        _fwrite(string, _handle)

    fun read_line(buf: byte[]): int
        if _fgets(buf, _handle) == false
            return 0
        for i in 0..buf.size()
            if buf[i] == 0
                return i
        return buf.size()

    fun flush()
        _fflush(_handle)

    fun seek(pos: int)
        _fseek(_handle, pos)

    fun tell(): int
        return _ftell(_handle)

#end
""",
  'hosted.folder': """#if HOSTED

@raw('''
#include <dirent.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>
''')

@extern('''({
    char __p[512];
    uint32_t __l = {path}.size < 511 ? {path}.size : 511;
    memcpy(__p, {path}.ptr, __l);
    __p[__l] = '\\0';
    (uint8_t*)opendir(__p);
})''')
fun _opendir(path: byte[]): &byte

@extern('''({
    struct dirent* __e = readdir((DIR*){handle});
    __e ? (uint8_t*)__e->d_name : (uint8_t*)NULL;
})''')
fun _readdir(handle: &byte): &byte

@extern("closedir((DIR*){handle})")
fun _closedir(handle: &byte)

@extern("(({handle}) != NULL)")
fun _dir_valid(handle: &byte): bool

// Create a directory. Returns true on success or if it already exists.
@extern('''({
    char __p[512];
    uint32_t __l = {path}.size < 511 ? {path}.size : 511;
    memcpy(__p, {path}.ptr, __l);
    __p[__l] = '\\0';
    int __r = mkdir(__p, 0755);
    __r == 0 || errno == EEXIST;
})''')
fun folder_create(path: byte[]): bool

class Folder
    var _handle: &byte

    // Open a directory. Returns true on success.
    fun open(path: byte[]): bool
        _handle = _opendir(path)
        return _dir_valid(_handle)

    // Copy the next entry name into buf. Returns bytes written, 0 when done.
    // Call in a loop until 0 is returned.
    fun next(buf: byte[]): int
        val name: &byte = _readdir(_handle)
        if !_dir_valid(name)
            return 0
        var i: int = 0
        while i < buf.size()
            val c: byte = name[i]
            if c == byte(0)
                break
            buf[i] = c
            i++
        return i

    fun close()
        _closedir(_handle)

#end
""",
  'hosted.signal': """#if HOSTED

@raw("#include <signal.h>")

var _exit_requested: bool = false

fun _on_exit_requested(sig: int)
    _exit_requested = true

@extern('''
    signal(SIGINT, (void(*)(int)){handler});
    signal(SIGTERM, (void(*)(int)){handler});
    #ifndef _WIN32
    signal(SIGHUP, (void(*)(int)){handler});
    #endif
''')
fun _watch_signals(handler: fun(int))

fun catch_signals()
    _watch_signals(_on_exit_requested)

fun exit_requested() bool
    return _exit_requested

#end
""",
  'hosted.time': """#if HOSTED

@raw('''
#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif
''')
@raw("#include <time.h>")

// Sleep for N microseconds.
// Windows: millisecond granularity via Sleep(). POSIX: microsecond via usleep().
@extern('''
#ifdef _WIN32
Sleep({us} / 1000)
#else
usleep({us})
#endif
''')
fun sleep_us(us: u32)

// Monotonic microseconds — suitable for deadline-based loops.
// Windows: QueryPerformanceCounter. POSIX: clock_gettime(CLOCK_MONOTONIC).
// Note: requires GCC/Clang statement expressions — MSVC not supported.
@extern('''({
#ifdef _WIN32
    LARGE_INTEGER _freq, _now;
    QueryPerformanceFrequency(&_freq);
    QueryPerformanceCounter(&_now);
    (int64_t)_now.QuadPart * 1000000LL / _freq.QuadPart;
#else
    struct timespec __ts;
    clock_gettime(CLOCK_MONOTONIC, &__ts);
    (int64_t)__ts.tv_sec * 1000000LL + __ts.tv_nsec / 1000LL;
#endif
})''')
fun time_us(): i64

#end
""",
  'log': """import console::*
import string::*

// Emit ESC[ + seq (e.g. "32m" → green, "33m" → orange, "31m" → red, "0m" → reset)
@inline
fun _esc(seq: byte[])
    write_byte(27)
    write_byte('[')
    write_string(seq)

// ── simple log (no format args) ───────────────────────────────────────────────

fun info(message: byte[])
    _esc("32m")
    write_string("[INFO] ")
    write_string(message)
    _esc("0m")
    write_byte(10)

fun warn(message: byte[])
    _esc("33m")
    write_string("[WARN] ")
    write_string(message)
    _esc("0m")
    write_byte(10)

fun error(message: byte[])
    _esc("31m")
    write_string("[ERROR] ")
    write_string(message)
    _esc("0m")
    write_byte(10)

// ── formatted log (build_string args) ────────────────────────────────────────
//
// Uses an internal 128-byte buffer — no buffer needed at the call site.
//
// Example:
//   var args: int[2] = [count, int(alive)]
//   info_args("count={0i} alive={1b}", args)

fun info_args(message: byte[], args: int[])
    val buf: byte[128]
    info(format(message, buf, args))

fun warn_args(message: byte[], args: int[])
    val buf: byte[128]
    warn(format(message, buf, args))

fun error_args(message: byte[], args: int[])
    val buf: byte[128]
    error(format(message, buf, args))
""",
  'math': """#if HOSTED || MCU32
@raw("#include <math.h>")

// ── Constants ─────────────────────────────────────────────────────────────────

const PI  := 3.14159265358979323846
const TAU := 6.28318530717958647692
const E   := 2.71828182845904523536
#end

// ── Generic min / max / clamp / abs ──────────────────────────────────────────

@inline
fun min<T>(a: T, b: T): T
    if a < b
        return a
    return b

@inline
fun max<T>(a: T, b: T): T
    if a > b
        return a
    return b

@inline
fun clamp<T>(value: T, low: T, high: T): T
    if value < low
        return low
    if value > high
        return high
    return value

@inline
fun abs<T>(value: T): T
    if value < 0
        return -value
    return value

// ── Q16 (16.16 fixed-point) rounding ─────────────────────────────────────────

@inline
fun floor_q16(value: q16): q16
    return value & -1.0

@inline
fun ceil_q16(value: q16): q16
    val result := value & -1.0
    if value != result
        return result + 1.0
    return result

@inline
fun round_q16(value: q16): q16
    return (value + 0.5) & -1.0

#if HOSTED || MCU32
// ── Float trig (radians) ──────────────────────────────────────────────────────

@extern("sinf")
fun sin(value: float): float

@extern("cosf")
fun cos(value: float): float

@extern("tanf")
fun tan(value: float): float

@extern("asinf")
fun asin(value: float): float

@extern("acosf")
fun acos(value: float): float

@extern("atanf")
fun atan(value: float): float

@extern("atan2f")
fun atan2(y: float, x: float): float

// ── Float power / root ────────────────────────────────────────────────────────

@extern("sqrtf")
fun sqrt(value: float): float

@extern("powf")
fun pow(base: float, exp: float): float

// ── Float rounding ────────────────────────────────────────────────────────────

@extern("floorf")
fun floor(value: float): float

@extern("ceilf")
fun ceil(value: float): float

@extern("roundf")
fun round(value: float): float
#end
""",
  'mcu32.allocator': """#if HOSTED || MCU32

class Allocator()
    var _memory: byte[] = {null, 0}
    var _cursor: int = 0

    fun init(mem: byte[])
        _memory = mem
        _cursor = 0

    @inline
    fun allocate<T>(): &T
        val size := sizeof<T>()
        if _cursor + size > _memory.size()
            return null
        val ptr := &T(&_memory[_cursor])
        _cursor = (_cursor + size + 3) & ~int(3)
        return ptr

    @inline
    fun allocate_array<T>(length: int): T[]
        val size := sizeof<T>() * length
        if _cursor + size > _memory.size()
            return {null, 0}
        val ptr := &T(&_memory[_cursor])
        _cursor = (_cursor + size + 3) & ~int(3)
        return {ptr, length}

    @inline
    fun reset()
        _cursor = 0

#end
""",
  'mcu32.collection': """#if HOSTED || MCU32
import mcu32.allocator::Allocator

// ── ArrayList ─────────────────────────────────────────────────────────────────
// Fixed-capacity list backed by an Allocator. Works on MCU and hosted.
// push/insert return false when full.

class ArrayList<T>()
    var _buffer: T[]
    var _size: int = 0

    fun init(alloc: &Allocator, capacity: int) bool
        _buffer = alloc.allocate_array<T>(capacity)
        if _buffer.size() == 0
            return false
        return true

    @inline
    fun push(value: T) bool
        if _size >= _buffer.size()
            return false
        _buffer[_size] = value
        _size += 1
        return true

    @inline
    fun pop() bool
        if _size == 0
            return false
        _size -= 1
        return true

    fun insert(i: int, value: T) bool
        if _size >= _buffer.size()
            return false
        if i > _size
            return false
        var j: int = _size
        while j > i
            _buffer[j] = _buffer[j - 1]
            j -= 1
        _buffer[i] = value
        _size += 1
        return true

    @inline
    fun get(i: int) T
        return _buffer[i]

    @inline
    fun set(i: int, value: T)
        _buffer[i] = value

    @inline
    fun top() T
        return _buffer[_size - 1]

    @inline
    fun size() int
        return _size

    @inline
    fun capacity() int
        return _buffer.size()

    @inline
    fun is_empty() bool
        return _size == 0

    @inline
    fun is_full() bool
        return _size >= _buffer.size()

    @inline
    fun clear()
        _size = 0

// ── RingBuffer ────────────────────────────────────────────────────────────────
// Fixed-capacity circular buffer backed by an Allocator.

class RingBuffer<T>()
    var _buffer: T[]
    var _head: int = 0
    var _tail: int = 0
    var _size: int = 0

    fun init(allocator: &Allocator, capacity: int) bool
        _buffer = allocator.allocate_array<T>(capacity)
        if _buffer.size() == 0
            return false
        return true

    @inline
    fun push(value: T) bool
        if _size >= _buffer.size()
            return false
        _buffer[_tail] = value
        _tail = (_tail + 1) % _buffer.size()
        _size += 1
        return true

    @inline
    fun pop() bool
        if _size == 0
            return false
        _head = (_head + 1) % _buffer.size()
        _size -= 1
        return true

    @inline
    fun peek() T
        return _buffer[_head]

    @inline
    fun size() int
        return _size

    @inline
    fun capacity() int
        return _buffer.size()

    @inline
    fun is_empty() bool
        return _size == 0

    @inline
    fun is_full() bool
        return _size >= _buffer.size()

#end
""",
  'memory': """@raw("#include <string.h>")

@extern("memset({dst}, {value}, {size})")
fun memory_set(dst: byte[], value: byte, size: int)

@extern("memcpy({dst}, {src}, {size})")
fun memory_copy(dst: byte[], src: byte[], size: int)

@extern("memmove({dst}, {src}, {size})")
fun memory_move(dst: byte[], src: byte[], size: int)

@inline
fun memory_zero(dst: byte[], size: int)
    memory_set(dst, byte(0), size)
""",
  'string': """// ── Comparison / search ───────────────────────────────────────────────────────

fun equals(a: byte[], b: byte[]): bool
    if a.size() != b.size()
        return false
    for i in 0..a.size()
        if a[i] != b[i]
            return false
    return true

fun starts_with(string: byte[], prefix: byte[]): bool
    if prefix.size() > string.size()
        return false
    for i in 0..prefix.size()
        if string[i] != prefix[i]
            return false
    return true

fun ends_with(string: byte[], suffix: byte[]): bool
    if suffix.size() > string.size()
        return false
    val offset := string.size() - suffix.size()
    for i in 0..suffix.size()
        if string[offset + i] != suffix[i]
            return false
    return true

fun index_of(string: byte[], character: byte): int
    for i in 0..string.size()
        if string[i] == character
            return i
    return -1

// ── Slicing ───────────────────────────────────────────────────────────────────

fun sub(string: byte[], start: int, len: int): byte[]
    return {string.ptr + start, len}

fun trim_start(string: byte[]): byte[]
    for i in 0..string.size()
        val c := string[i]
        if c != 32 && c != 9 && c != 10 && c != 13
            return {string.ptr + i, string.size() - i}
    return {string.ptr, 0}

fun trim_end(string: byte[]): byte[]
    if string.size() == 0
        return string
    var i := string.size() - 1
    while i > 0
        val c := string[i]
        if c != 32 && c != 9 && c != 10 && c != 13
            return {string.ptr, i + 1}
        i -= 1
    val c := string[0]
    if c != 32 && c != 9 && c != 10 && c != 13
        return {string.ptr, 1}
    return {string.ptr, 0}

fun trim(string: byte[]): byte[]
    return trim_end(trim_start(string))

// ── Tokenization ──────────────────────────────────────────────────────────────

// Returns the token starting at `start` up to (not including) the next `delim`
// or end of string.
fun token(string: byte[], start: int, delim: byte): byte[]
    for i in start..string.size()
        if string[i] == delim
            return {string.ptr + start, i - start}
    return {string.ptr + start, string.size() - start}

// Advances past any `delim` bytes starting at `start`. Use after token() to
// move to the next field.
fun skip(string: byte[], start: int, delim: byte): int
    for i in start..string.size()
        if string[i] != delim
            return i
    return string.size()

// ── Number parsing ────────────────────────────────────────────────────────────

fun parse_u32(string: byte[]): u32
    var result: u32 = 0
    for i in 0..string.size()
        val c := string[i]
        if c < 48 || c > 57
            return result
        result = result * 10 + u32(c - 48)
    return result

fun parse_int(string: byte[]): int
    if string.size() == 0
        return 0
    if string[0] == 45
        val abs := parse_u32({string.ptr + 1, string.size() - 1})
        return int(-abs)
    return int(parse_u32(string))

// ── Number formatting ─────────────────────────────────────────────────────────

// Writes decimal representation of `v` into `buf`. Returns number of bytes
// written. buf must be at least 10 bytes.
fun format_u32(buf: byte[], value: u32): int
    if value == 0
        buf[0] = 48
        return 1
    var tmp: byte[10]
    var len: int = 0
    var n := value
    while n > 0
        tmp[len] = byte(48 + n % 10)
        n = n / 10
        len += 1
    for i in 0..len
        buf[i] = tmp[len - 1 - i]
    return len

// Writes decimal representation of `v` into `buf`. Returns bytes written.
// buf must be at least 11 bytes.
fun format_int(buf: byte[], value: int): int
    if value < 0
        buf[0] = 45
        val written := format_u32({buf.ptr + 1, buf.size() - 1}, u32(-value))
        return written + 1
    return format_u32(buf, u32(value))

// ── String building ───────────────────────────────────────────────────────────
//
// Renders `text` into `buf`, replacing {Ni} {Nu} {Nf} {Nd} {Nb} placeholders.
// All args are stored as int — the type specifier controls formatting:
//   {0i}  signed int (default when no specifier)
//   {0u}  unsigned int
//   {0f}  float       — pass bits via float_bits(v)
//   {0d}  q16 (16.16) — pass as int(v) (q16 is int internally)
//   {0b}  bool        — prints "true" / "false"
//
// Returns a byte[] slice into buf with the final length.
//
// Example:
//   var buf:  byte[64]
//   var args: int[3] = {hp, max_hp, int(alive)}
//   val s := build_string("HP: {0i}/{1i} alive={2b}", buf, args)

// Bit-cast helpers — raw 32-bit reinterpret, no value conversion.
@raw("static inline int32_t __mp_float_to_bits(float f) { int32_t v; __builtin_memcpy(&v, &f, 4); return v; }")
@raw("static inline float __mp_bits_to_float(int32_t v) { float f; __builtin_memcpy(&f, &v, 4); return f; }")

@extern("__mp_float_to_bits")
fun float_bits(value: float) int

@extern("__mp_bits_to_float")
fun _bits_to_float(value: int) float

// q16 and int share the same 32-bit representation — this is the explicit,
// intention-clear way to pass a q16 value into an int[] args array.
// Do NOT use int(my_q16): semantically that means "extract integer part".
@extern("((int32_t){value})")
fun q16_bits(value: q16) int

fun _format_float(buf: byte[], value: float) int
    var bi: int = 0
    var abs: float = value
    if value < 0.0
        buf[bi] = 45  // '-'
        bi += 1
        abs = 0.0 - value
    val int_part := int(abs)
    bi += format_int({buf.ptr + bi, buf.size() - bi}, int_part)
    buf[bi] = 46  // '.'
    bi += 1
    var frac: float = abs - float(int_part)
    for d in 0..4
        frac = frac * 10.0
        val digit := int(frac)
        buf[bi] = byte(digit + 48)
        bi += 1
        frac = frac - float(digit)
    return bi

fun _format_q16(buf: byte[], value: int) int
    var bi: int = 0
    var abs: u32 = 0
    if value < 0
        buf[bi] = 45  // '-'
        bi += 1
        abs = u32(0 - value)
    else
        abs = u32(value)
    bi += format_u32({buf.ptr + bi, buf.size() - bi}, abs >> 16)
    buf[bi] = 46  // '.'
    bi += 1
    var frac: u32 = abs & 0xFFFF
    for d in 0..4
        frac *= 10
        buf[bi] = byte((frac >> 16) + 48)
        bi += 1
        frac = frac & 0xFFFF
    return bi

fun _format_bool(buf: byte[], value: int) int
    if value != 0
        buf[0] = 't'
        buf[1] = 'r'
        buf[2] = 'u'
        buf[3] = 'e'
        return 4
    buf[0] = 'f'
    buf[1] = 'a'
    buf[2] = 'l'
    buf[3] = 's'
    buf[4] = 'e'
    return 5

fun format(text: byte[], buf: byte[], args: int[]): byte[]
    var ti: int = 0
    var bi: int = 0
    while ti < text.size() && bi < buf.size()
        val c := text[ti]
        if c == '{'
            ti += 1
            var idx: int = 0
            while ti < text.size() && text[ti] != '}' && text[ti] != 'i' && text[ti] != 'u' && text[ti] != 'f' && text[ti] != 'd' && text[ti] != 'b'
                idx = idx * 10 + int(text[ti]) - 48
                ti += 1
            var spec: byte = 'i'
            if ti < text.size() && text[ti] != '}'
                spec = text[ti]
                ti += 1
            ti += 1  // skip '}'
            if idx >= 0 && idx < args.size()
                val sub := {buf.ptr + bi, buf.size() - bi}
                var written: int = 0
                if spec == 'u'
                    written = format_u32(sub, u32(args[idx]))
                else if spec == 'f'
                    written = _format_float(sub, _bits_to_float(args[idx]))
                else if spec == 'd'
                    written = _format_q16(sub, args[idx])
                else if spec == 'b'
                    written = _format_bool(sub, args[idx])
                else
                    written = format_int(sub, args[idx])
                bi += written
        else
            buf[bi] = c
            bi += 1
            ti += 1
    return {buf.ptr, bi}
""",
  'test': """import console::*

// ── global counters (test-level, not assert-level) ────────────────────────────

var _succeeded: u32 = 0
var _failed: u32 = 0

// ── per-test state ────────────────────────────────────────────────────────────

var _current_name: byte[] = ""
var _current_failed: u32 = 0

// failure buffer: up to 8 failures per test
var _buf_count: u32 = 0
var _buf_lines: u32[8]
var _buf_files: byte[][8]
var _buf_exprs: byte[][8]

// ── called by generated assert code ──────────────────────────────────────────

fun _test_pass()
    // counted at test level in _test_end, nothing to do per assert

fun _test_fail(file: byte[], line: u32, expr: byte[])
    if _buf_count < 8
        _buf_files[_buf_count] = file
        _buf_lines[_buf_count] = line
        _buf_exprs[_buf_count] = expr
        _buf_count += 1
    _current_failed += 1

// ── called by generated test main() ──────────────────────────────────────────

fun _test_begin(name: byte[])
    _current_name = name
    _current_failed = 0
    _buf_count = 0

fun _test_end()
    if _current_failed == 0
        write_string("\\x1b[32mP:")
        write_string(_current_name)
        write_string("\\x1b[0m")
        write_byte(10)
        _succeeded += 1
    else
        write_string("\\x1b[31mF:")
        write_string(_current_name)
        write_string("\\x1b[0m")
        write_byte(10)
        var i: u32 = 0
        while i < _buf_count
            write_string("  ")
            write_string(_buf_files[i])
            write_string(":")
            write_u32(_buf_lines[i])
            write_string(": ")
            write_string(_buf_exprs[i])
            write_byte(10)
            i += 1
        _failed += 1

fun _report() int
    write_string("DONE ")
    write_u32(_succeeded)
    write_string("/")
    write_u32(_succeeded + _failed)
    write_byte(10)
    if _failed > 0
        return 1
    return 0
""",
};
