// AUTO-GENERATED by tool/gen_stdlib.dart — do not edit manually.
// Run: dart tool/gen_stdlib.dart

/// Embedded standard library sources, keyed by module path.
/// Excludes '*_test.mpd' files.
const Map<String, String> kStdlib = {
  'collection': r'''
import memory::Allocator
#if HOSTED
import memory::HeapAllocator
#end

// ── ArrayList ─────────────────────────────────────────────────────────────────
// Fixed-capacity list backed by an Allocator. Works on MCU and hosted.
// push/insert return false when full.

class ArrayList<T>()
    var _buffer: T[]
    var _size: u32 = 0

    fun init(alloc: &Allocator, capacity: u32) bool
        _buffer = alloc.allocate_array<T>(capacity)
        if _buffer.size() == 0
            return false
        return true

    @inline
    fun push(value: T) bool
        if _size >= _buffer.size()
            return false
        _buffer[_size] = value
        _size += 1
        return true

    @inline
    fun pop() bool
        if _size == 0
            return false
        _size -= 1
        return true

    fun insert(i: u32, value: T) bool
        if _size >= _buffer.size()
            return false
        if i > _size
            return false
        var j: u32 = _size
        while j > i
            _buffer[j] = _buffer[j - 1]
            j -= 1
        _buffer[i] = value
        _size += 1
        return true

    @inline
    fun get(i: u32) T
        return _buffer[i]

    @inline
    fun set(i: u32, value: T)
        _buffer[i] = value

    @inline
    fun top() T
        return _buffer[_size - 1]

    @inline
    fun size() u32
        return _size

    @inline
    fun capacity() u32
        return _buffer.size()

    @inline
    fun is_empty() bool
        return _size == 0

    @inline
    fun is_full() bool
        return _size >= _buffer.size()

    @inline
    fun clear()
        _size = 0

// ── HeapList ──────────────────────────────────────────────────────────────────
// Growable list backed by HeapAllocator. HOSTED only.
// push/insert auto-grow on full; return false only on allocation failure.

#if HOSTED
class HeapList<T>()
    var _buffer: T[]
    var _size: u32 = 0
    var _heap: &HeapAllocator

    fun init(heap: &HeapAllocator)
        _heap = heap
        _buffer = heap.allocate_array<T>(8)

    @inline
    fun push(value: T) bool
        if _size >= _buffer.size()
            _buffer = _heap.realloc_array<T>(_buffer, _buffer.size() * 2)
            if _buffer.size() == 0
                return false
        _buffer[_size] = value
        _size += 1
        return true

    @inline
    fun pop() bool
        if _size == 0
            return false
        _size -= 1
        return true

    fun insert(i: u32, value: T) bool
        if i > _size
            return false
        if _size >= _buffer.size()
            _buffer = _heap.realloc_array<T>(_buffer, _buffer.size() * 2)
            if _buffer.size() == 0
                return false
        var j: u32 = _size
        while j > i
            _buffer[j] = _buffer[j - 1]
            j -= 1
        _buffer[i] = value
        _size += 1
        return true

    @inline
    fun get(i: u32) T
        return _buffer[i]

    @inline
    fun set(i: u32, value: T)
        _buffer[i] = value

    @inline
    fun top() T
        return _buffer[_size - 1]

    @inline
    fun size() u32
        return _size

    @inline
    fun capacity() u32
        return _buffer.size()

    @inline
    fun is_empty() bool
        return _size == 0

    @inline
    fun clear()
        _size = 0

    fun free()
        _heap.free_array<T>(_buffer)
        _buffer = {null, 0}
        _size = 0
#end

// ── HeapMap ───────────────────────────────────────────────────────────────────
// Hash map with string (u8[]) keys and generic values. HOSTED only.
// Uses FNV-1a hashing, linear probing, 75% load-factor resize.
// Keys are copied into an owned flat byte pool — keys need not outlive the map.

class HeapMap<T>()
    var _key_start: u32[]   // offset into _pool per slot
    var _key_len: u32[]     // key length per slot
    var _pool: u8[]         // flat owned key byte storage
    var _pool_used: u32 = 0
    var _values: T[]
    var _state: u8[]        // 0=empty 1=used 2=deleted
    var _size: u32 = 0
    var _capacity: u32 = 0
    var _heap: &HeapAllocator

    fun init(heap: &HeapAllocator)
        _heap = heap
        _capacity = 8
        _key_start = heap.allocate_array<u32>(_capacity)
        _key_len = heap.allocate_array<u32>(_capacity)
        _pool = heap.allocate_array<u8>(128)
        _values = heap.allocate_array<T>(_capacity)
        _state = heap.allocate_array<u8>(_capacity)
        var i: u32 = 0
        while i < _capacity
            _state[i] = 0
            i += 1

    fun _hash(key: u8[]): u32
        var h: u32 = 2166136261
        var i: u32 = 0
        while i < key.size()
            h = h ^ u32(key[i])
            h = h * 16777619
            i += 1
        return h % _capacity

    fun _key_eq(slot: u32, key: u8[]): bool
        if _key_len[slot] != key.size()
            return false
        val start := _key_start[slot]
        var i: u32 = 0
        while i < key.size()
            if _pool[start + i] != key[i]
                return false
            i += 1
        return true

    // Returns slot for key (existing) or first available slot (empty/tombstone).
    // Returns _capacity if the table is completely full with no match.
    fun _find_slot(key: u8[]): u32
        var slot := _hash(key)
        var first_del: u32 = _capacity
        var i: u32 = 0
        while i < _capacity
            if _state[slot] == 0
                if first_del != _capacity
                    return first_del
                return slot
            if _state[slot] == 2
                if first_del == _capacity
                    first_del = slot
            else
                if _key_eq(slot, key)
                    return slot
            slot = (slot + 1) % _capacity
            i += 1
        if first_del != _capacity
            return first_del
        return _capacity

    fun contains(key: u8[]): bool
        if _capacity == 0
            return false
        val slot := _find_slot(key)
        if slot >= _capacity
            return false
        return _state[slot] == 1

    // Returns value. Caller must check contains() first; behaviour is
    // undefined when the key is absent.
    fun get(key: u8[]): T
        val slot := _find_slot(key)
        return _values[slot]

    fun set(key: u8[], value: T)
        if _size * 4 >= _capacity * 3
            _grow()
        val slot := _find_slot(key)
        if slot >= _capacity
            return
        if _state[slot] != 1
            _pool_ensure(key.size())
            val start := _pool_used
            var i: u32 = 0
            while i < key.size()
                _pool[start + i] = key[i]
                i += 1
            _pool_used += key.size()
            _key_start[slot] = start
            _key_len[slot] = key.size()
            _state[slot] = 1
            _size += 1
        _values[slot] = value

    fun remove(key: u8[]): bool
        if _capacity == 0
            return false
        val slot := _find_slot(key)
        if slot >= _capacity
            return false
        if _state[slot] != 1
            return false
        _state[slot] = 2
        _size -= 1
        return true

    fun size(): u32
        return _size

    fun _pool_ensure(needed: u32)
        if _pool_used + needed <= _pool.size()
            return
        var new_size := _pool.size() * 2
        if new_size < _pool_used + needed
            new_size = _pool_used + needed
        _pool = _heap.realloc_array<u8>(_pool, new_size)

    fun _grow()
        val old_key_start := _key_start
        val old_key_len := _key_len
        val old_pool := _pool
        val old_values := _values
        val old_state := _state
        val old_cap := _capacity
        _capacity = old_cap * 2
        _key_start = _heap.allocate_array<u32>(_capacity)
        _key_len = _heap.allocate_array<u32>(_capacity)
        _pool = _heap.allocate_array<u8>(_pool_used + 64)
        _pool_used = 0
        _values = _heap.allocate_array<T>(_capacity)
        _state = _heap.allocate_array<u8>(_capacity)
        _size = 0
        var i: u32 = 0
        while i < _capacity
            _state[i] = 0
            i += 1
        i = 0
        while i < old_cap
            if old_state[i] == 1
                val s := old_key_start[i]
                val l := old_key_len[i]
                val key := {&old_pool[s], l}
                set(key, old_values[i])
            i += 1
        _heap.free_array<u32>(old_key_start)
        _heap.free_array<u32>(old_key_len)
        _heap.free_array<u8>(old_pool)
        _heap.free_array<T>(old_values)
        _heap.free_array<u8>(old_state)

    fun free()
        _heap.free_array<u32>(_key_start)
        _heap.free_array<u32>(_key_len)
        _heap.free_array<u8>(_pool)
        _heap.free_array<T>(_values)
        _heap.free_array<u8>(_state)
        _key_start = {null, 0}
        _key_len = {null, 0}
        _pool = {null, 0}
        _values = {null, 0}
        _state = {null, 0}
        _size = 0
        _capacity = 0

// ── RingBuffer ────────────────────────────────────────────────────────────────
// Fixed-capacity circular buffer backed by an Allocator.

class RingBuffer<T>()
    var _buffer: T[]
    var _head: u32 = 0
    var _tail: u32 = 0
    var _size: u32 = 0

    fun init(allocator: &Allocator, capacity: u32) bool
        _buffer = allocator.allocate_array<T>(capacity)
        if _buffer.size() == 0
            return false
        return true

    @inline
    fun push(value: T) bool
        if _size >= _buffer.size()
            return false
        _buffer[_tail] = value
        _tail = (_tail + 1) % _buffer.size()
        _size += 1
        return true

    @inline
    fun pop() bool
        if _size == 0
            return false
        _head = (_head + 1) % _buffer.size()
        _size -= 1
        return true

    @inline
    fun peek() T
        return _buffer[_head]

    @inline
    fun size() u32
        return _size

    @inline
    fun capacity() u32
        return _buffer.size()

    @inline
    fun is_empty() bool
        return _size == 0

    @inline
    fun is_full() bool
        return _size >= _buffer.size()
''',
  'console': r'''
// ── transport ────────────────────────────────────────────────────────────────
//
// HOSTED: write_byte maps to putchar.
// MCU:         platform module must provide write_byte(b: u8).

#if HOSTED

@include("stdio.h")

@extern("putchar({b})")
fun write_byte(b: u8)

#else

// Forward declaration — linker resolves from platform code (UART, UDP, etc.)
fun write_byte(b: u8)

#end

// ── primitives ───────────────────────────────────────────────────────────────

fun println()
    write_byte(10)

fun print_str(s: u8[])
    var i: u32 = 0
    while i < s.size()
        write_byte(s[i])
        i += 1

fun print_bool(v: bool)
    if v
        write_byte('t')
        write_byte('r')
        write_byte('u')
        write_byte('e')
    else
        write_byte('f')
        write_byte('a')
        write_byte('l')
        write_byte('s')
        write_byte('e')

// ── unsigned integers ─────────────────────────────────────────────────────────

fun print_u64(v: u64)
    var buf: u8[20]
    var i: i32 = 19
    if v == 0
        write_byte('0')
        return
    while v > 0
        buf[i] = u8(v % 10 + 48)
        v = v / 10
        i -= 1
    var j: i32 = i + 1
    while j < 20
        write_byte(buf[j])
        j += 1

fun print_u32(v: u32)
    print_u64(u64(v))

fun print_u16(v: u16)
    print_u64(u64(v))

fun print_u8(v: u8)
    print_u64(u64(v))

// ── signed integers ───────────────────────────────────────────────────────────

fun print_i64(v: i64)
    if v < 0
        write_byte('-')
        print_u64(u64(i64(0) - v))
    else
        print_u64(u64(v))

fun print_i32(v: i32)
    print_i64(i64(v))

fun print_i16(v: i16)
    print_i64(i64(v))

fun print_i8(v: i8)
    print_i64(i64(v))

// ── float ─────────────────────────────────────────────────────────────────────
//
// Naive float print: separates integer and fractional parts, extracts decimal
// digits by successive * 10. Accurate to ~6 significant digits (float precision).
// Does not handle NaN or Inf.

fun print_float(v: float, decimals: u32)
    var abs: float = v
    if v < 0.0
        write_byte('-')
        abs = 0.0 - v
    val int_part := i32(abs)
    print_i32(int_part)
    if decimals > 0
        write_byte('.')
        var frac: float = abs - float(int_part)
        var i: u32 = 0
        while i < decimals
            frac = frac * 10.0
            val digit := i32(frac)
            write_byte(u8(digit + 48))
            frac = frac - float(digit)
            i += 1

// ── fixed-point ───────────────────────────────────────────────────────────────
//
// 16.16 fixed-point: high 16 bits = integer part, low 16 bits = fractional part.
// e.g. print_fixed(0x00018000, 2) → "1.50"   (1 + 32768/65536)
//      print_fixed(0xFFFE8000, 2) → "-1.50"
//
// decimals: how many fractional decimal digits to emit (0 = integer only).

fun print_fixed(v: fixed, decimals: u32)
    var abs: u32 = 0
    if v < 0
        write_byte('-')
        abs = u32(0 - v)
    else
        abs = u32(v)

    // integer part: high 16 bits
    print_u32(abs >> 16)

    if decimals > 0
        write_byte('.')
        // fractional part: low 16 bits
        // extract each decimal digit: multiply frac by 10, digit = high 16 bits
        var frac: u32 = abs & 0xFFFF
        var i: u32 = 0
        while i < decimals
            frac *= 10
            write_byte(u8((frac >> 16) + 48))
            frac = frac & 0xFFFF
            i += 1
''',
  'file': r'''
@include("stdio.h")

@extern("(uint8_t*)fopen((const char*){path}.ptr, (const char*){mode}.ptr)")
fun _fopen(path: u8[], mode: u8[]): &u8

@extern("fclose((FILE*){handle})")
fun _fclose(handle: &u8)

@extern("(uint32_t)fread({buf}.ptr, 1, {buf}.size, (FILE*){handle})")
fun _fread(buf: u8[], handle: &u8): u32

@extern("(uint32_t)fwrite({buf}.ptr, 1, {buf}.size, (FILE*){handle})")
fun _fwrite(buf: u8[], handle: &u8): u32

@extern("(fgets((char*){buf}.ptr, (int){buf}.size, (FILE*){handle}) != NULL)")
fun _fgets(buf: u8[], handle: &u8): bool

@extern("fflush((FILE*){handle})")
fun _fflush(handle: &u8)

@extern("fseek((FILE*){handle}, (long){pos}, 0)")
fun _fseek(handle: &u8, pos: u32)

@extern("(uint32_t)ftell((FILE*){handle})")
fun _ftell(handle: &u8): u32

@extern("(({handle}) != NULL)")
fun _ptr_valid(handle: &u8): bool

const READ        = "r"
const WRITE       = "w"
const APPEND      = "a"
const READ_WRITE  = "r+"
const WRITE_READ  = "w+"
const APPEND_READ = "a+"

class File()
    var _handle: &u8
    var _open: bool

    fun open(path: u8[], mode: u8[]): bool
        _handle = _fopen(path, mode)
        _open = _ptr_valid(_handle)
        return _open

    fun close()
        if _open
            _fclose(_handle)
            _open = false

    @inline
    fun is_open(): bool
        return _open

    fun read_bytes(buf: u8[]): u32
        return _fread(buf, _handle)

    fun write_bytes(buf: u8[]): u32
        return _fwrite(buf, _handle)

    @inline
    fun write_str(s: u8[])
        _fwrite(s, _handle)

    fun read_line(buf: u8[]): u32
        if _fgets(buf, _handle) == false
            return 0
        var i: u32 = 0
        while i < buf.size()
            if buf[i] == 0
                return i
            i += 1
        return buf.size()

    fun flush()
        _fflush(_handle)

    fun seek(pos: u32)
        _fseek(_handle, pos)

    fun tell(): u32
        return _ftell(_handle)
''',
  'math': r'''
@include("math.h")

// ── Constants ─────────────────────────────────────────────────────────────────

const PI  := 3.14159265358979323846
const TAU := 6.28318530717958647692
const E   := 2.71828182845904523536

// ── Generic min / max / clamp / abs ──────────────────────────────────────────

@inline
fun min<T>(a: T, b: T): T
    if a < b
        return a
    return b

@inline
fun max<T>(a: T, b: T): T
    if a > b
        return a
    return b

@inline
fun clamp<T>(v: T, lo: T, hi: T): T
    if v < lo
        return lo
    if v > hi
        return hi
    return v

@inline
fun abs<T>(v: T): T
    if v < 0
        return -v
    return v

// ── Float trig (radians) ──────────────────────────────────────────────────────

@extern("sinf({x})")
fun sin(x: float): float

@extern("cosf({x})")
fun cos(x: float): float

@extern("tanf({x})")
fun tan(x: float): float

@extern("asinf({x})")
fun asin(x: float): float

@extern("acosf({x})")
fun acos(x: float): float

@extern("atanf({x})")
fun atan(x: float): float

@extern("atan2f({y}, {x})")
fun atan2(y: float, x: float): float

// ── Float power / root ────────────────────────────────────────────────────────

@extern("sqrtf({x})")
fun sqrt(x: float): float

@extern("powf({base}, {exp})")
fun pow(base: float, exp: float): float

// ── Float rounding ────────────────────────────────────────────────────────────

@extern("floorf({x})")
fun floor(x: float): float

@extern("ceilf({x})")
fun ceil(x: float): float

@extern("roundf({x})")
fun round(x: float): float

// ── Fixed-point rounding ──────────────────────────────────────────────────────

@inline
fun floor_fixed(v: fixed): fixed
    return v & -1.0

@inline
fun ceil_fixed(v: fixed): fixed
    val f := v & -1.0
    if v != f
        return f + 1.0
    return f

@inline
fun round_fixed(v: fixed): fixed
    return (v + 0.5) & -1.0
''',
  'memory': r'''
#if HOSTED

@include("stdlib.h")

@extern("malloc")
fun _malloc(size: u32): &u8

@extern("realloc")
fun _realloc(ptr: &u8, new_size: u32): &u8

@extern("free")
fun _free(ptr: &u8)

// Heap allocator for growable containers (HOSTED only).
// Wraps malloc/realloc/free. Has no state — store a pointer to share ownership.
class HeapAllocator()
    var _pad: u8 = 0    // keeps struct non-empty

    fun allocate_array<T>(length: u32): T[]
        val size := sizeof<T>() * length
        val ptr := &T(_malloc(size))
        return {ptr, length}

    fun realloc_array<T>(arr: T[], new_length: u32): T[]
        val size := sizeof<T>() * new_length
        val ptr := &T(_realloc(&u8(arr.ptr), size))
        return {ptr, new_length}

    fun free_array<T>(arr: T[])
        _free(&u8(arr.ptr))

class Allocator()
    var _ptr: &u8 = null
    var _capacity: u32 = 0
    var _cursor: u32 = 0

    fun init(capacity: u32)
        _ptr = _malloc(capacity)
        _capacity = capacity

    fun allocate<T>(): &T
        val size := sizeof<T>()
        if _check_buffer(size)
            val ptr := &T(&_ptr[_cursor])
            _cursor = _align(_cursor + size, 8)
            return ptr
        return null

    fun allocate_array<T>(length: u32): T[]
        val size := sizeof<T>() * length
        if _check_buffer(size)
            val ptr := &T(&_ptr[_cursor])
            _cursor = _align(_cursor + size, 8)
            return {ptr, length}
        return {null, 0}

    fun reset()
        _cursor = 0

    fun _align(cursor: u32, align: u32): u32
        return (cursor + align - 1) & ~(align - 1)

    fun _check_buffer(size: u32) bool
        val aligned := _align(_cursor + size, 8)
        if aligned > _capacity
            _capacity = _capacity * 2
            _ptr = _realloc(_ptr, _capacity)
            if _ptr == null
                return false
        return true

#else

class Allocator(val _memory: u8[])
    var _cursor: u32 = 0

    @inline
    fun allocate<T>(): &T
        val size := sizeof<T>()
        if _cursor + size > _memory.size()
            return null
        val ptr := &T(&_memory[_cursor])
        _cursor = (_cursor + size + 3) & ~u32(3)
        return ptr

    @inline
    fun allocate_array<T>(length: u32): T[]
        val size := sizeof<T>() * length
        if _cursor + size > _memory.size()
            return {null, 0}
        val ptr := &T(&_memory[_cursor])
        _cursor = (_cursor + size + 3) & ~u32(3)
        return {ptr, length}

    @inline
    fun reset()
        _cursor = 0

#end
''',
  'string': r'''
// ── Comparison / search ───────────────────────────────────────────────────────

fun equals(a: u8[], b: u8[]): bool
    if a.size() != b.size()
        return false
    var i: u32 = 0
    while i < a.size()
        if a[i] != b[i]
            return false
        i += 1
    return true

fun starts_with(s: u8[], prefix: u8[]): bool
    if prefix.size() > s.size()
        return false
    var i: u32 = 0
    while i < prefix.size()
        if s[i] != prefix[i]
            return false
        i += 1
    return true

fun ends_with(s: u8[], suffix: u8[]): bool
    if suffix.size() > s.size()
        return false
    val offset := s.size() - suffix.size()
    var i: u32 = 0
    while i < suffix.size()
        if s[offset + i] != suffix[i]
            return false
        i += 1
    return true

fun index_of(s: u8[], c: u8): i32
    var i: u32 = 0
    while i < s.size()
        if s[i] == c
            return i32(i)
        i += 1
    return -1

// ── Slicing ───────────────────────────────────────────────────────────────────

fun sub(s: u8[], start: u32, len: u32): u8[]
    return {s.ptr + start, len}

fun trim_start(s: u8[]): u8[]
    var i: u32 = 0
    while i < s.size()
        val c := s[i]
        if c != 32 && c != 9 && c != 10 && c != 13
            return {s.ptr + i, s.size() - i}
        i += 1
    return {s.ptr, 0}

fun trim_end(s: u8[]): u8[]
    if s.size() == 0
        return s
    var i := s.size() - 1
    while i > 0
        val c := s[i]
        if c != 32 && c != 9 && c != 10 && c != 13
            return {s.ptr, i + 1}
        i -= 1
    val c := s[0]
    if c != 32 && c != 9 && c != 10 && c != 13
        return {s.ptr, 1}
    return {s.ptr, 0}

fun trim(s: u8[]): u8[]
    return trim_end(trim_start(s))

// ── Tokenization ──────────────────────────────────────────────────────────────

// Returns the token starting at `start` up to (not including) the next `delim`
// or end of string.
fun token(s: u8[], start: u32, delim: u8): u8[]
    var i := start
    while i < s.size()
        if s[i] == delim
            return {s.ptr + start, i - start}
        i += 1
    return {s.ptr + start, s.size() - start}

// Advances past any `delim` bytes starting at `start`. Use after token() to
// move to the next field.
fun skip(s: u8[], start: u32, delim: u8): u32
    var i := start
    while i < s.size()
        if s[i] != delim
            return i
        i += 1
    return s.size()

// ── Number parsing ────────────────────────────────────────────────────────────

fun parse_u32(s: u8[]): u32
    var result: u32 = 0
    var i: u32 = 0
    while i < s.size()
        val c := s[i]
        if c < 48 || c > 57
            return result
        result = result * 10 + u32(c - 48)
        i += 1
    return result

fun parse_i32(s: u8[]): i32
    if s.size() == 0
        return 0
    if s[0] == 45
        val abs := parse_u32({s.ptr + 1, s.size() - 1})
        return i32(-abs)
    return i32(parse_u32(s))

// ── Number formatting ─────────────────────────────────────────────────────────

// Writes decimal representation of `v` into `buf`. Returns number of bytes
// written. buf must be at least 10 bytes.
fun format_u32(buf: u8[], v: u32): u32
    if v == 0
        buf[0] = 48
        return 1
    var tmp: u8[10]
    var len: u32 = 0
    var n := v
    while n > 0
        tmp[len] = u8(48 + n % 10)
        n = n / 10
        len += 1
    var i: u32 = 0
    while i < len
        buf[i] = tmp[len - 1 - i]
        i += 1
    return len

// Writes decimal representation of `v` into `buf`. Returns bytes written.
// buf must be at least 11 bytes.
fun format_i32(buf: u8[], v: i32): u32
    if v < 0
        buf[0] = 45
        val written := format_u32({buf.ptr + 1, buf.size() - 1}, u32(-v))
        return written + 1
    return format_u32(buf, u32(v))
''',
  'test': r'''
import console::*

// ── global counters (test-level, not assert-level) ────────────────────────────

var _succeeded: u32 = 0
var _failed: u32 = 0

// ── per-test state ────────────────────────────────────────────────────────────

var _current_name: u8[] = ""
var _current_failed: u32 = 0

// failure buffer: up to 8 failures per test
var _buf_count: u32 = 0
var _buf_lines: u32[8]
var _buf_files: u8[][8]
var _buf_exprs: u8[][8]

// ── called by generated assert code ──────────────────────────────────────────

fun _test_pass()
    // counted at test level in _test_end, nothing to do per assert

fun _test_fail(file: u8[], line: u32, expr: u8[])
    if _buf_count < 8
        _buf_files[_buf_count] = file
        _buf_lines[_buf_count] = line
        _buf_exprs[_buf_count] = expr
        _buf_count += 1
    _current_failed += 1

// ── called by generated test main() ──────────────────────────────────────────

fun _test_begin(name: u8[])
    _current_name = name
    _current_failed = 0
    _buf_count = 0

fun _test_end()
    if _current_failed == 0
        print_str("\x1b[32mP:")
        print_str(_current_name)
        print_str("\x1b[0m")
        println()
        _succeeded += 1
    else
        print_str("\x1b[31mF:")
        print_str(_current_name)
        print_str("\x1b[0m")
        println()
        var i: u32 = 0
        while i < _buf_count
            print_str("  ")
            print_str(_buf_files[i])
            print_str(":")
            print_u32(_buf_lines[i])
            print_str(": ")
            print_str(_buf_exprs[i])
            println()
            i += 1
        _failed += 1

fun _report() i32
    print_str("DONE ")
    print_u32(_succeeded)
    print_str("/")
    print_u32(_succeeded + _failed)
    println()
    if _failed > 0
        return 1
    return 0
''',
};
