// Generates lib/src/stdlib_embedded.dart from micro-panda/std/src/*.mpd
// Run: dart tool/gen_stdlib.dart
import 'dart:io';
import 'package:path/path.dart' as p;

void main() {
  final scriptDir = p.dirname(Platform.script.toFilePath());
  final repoRoot = p.normalize(p.join(scriptDir, '..'));
  final stdSrc = p.join(repoRoot, 'micro-panda', 'std', 'src');
  final outFile = p.join(repoRoot, 'lib', 'src', 'stdlib_embedded.dart');

  final files = Directory(stdSrc)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.mpd') && !f.path.endsWith('_test.mpd'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final buf = StringBuffer();
  buf.writeln('// AUTO-GENERATED by tool/gen_stdlib.dart — do not edit manually.');
  buf.writeln('// Run: dart tool/gen_stdlib.dart');
  buf.writeln();
  buf.writeln('/// Embedded standard library sources, keyed by module path.');
  buf.writeln("/// Excludes '*_test.mpd' files.");
  buf.writeln('const Map<String, String> kStdlib = {');

  for (final file in files) {
    final name = p.basenameWithoutExtension(file.path);
    final content = file.readAsStringSync();
    buf.writeln("  '$name': r'''");
    buf.write(content);
    if (!content.endsWith('\n')) buf.writeln();
    buf.writeln("''',");
  }

  buf.writeln('};');

  File(outFile).writeAsStringSync(buf.toString());
  print('Generated $outFile (${files.length} modules: '
      '${files.map((f) => p.basenameWithoutExtension(f.path)).join(', ')})');
}
