// Generates lib/src/stdlib_embedded.dart from micro-panda/std/src/**/*.mpd
// Run: dart tool/gen_stdlib.dart
import 'dart:io';
import 'package:path/path.dart' as p;

/// djb2-variant hash of all key+content pairs (sorted for determinism).
String _computeHash(List<({String key, String content})> entries) {
  var h = 5381;
  final sorted = entries.toList()..sort((a, b) => a.key.compareTo(b.key));
  for (final e in sorted) {
    for (final c in (e.key + e.content).codeUnits) {
      h = ((h << 5) + h + c) & 0x7FFFFFFF;
    }
  }
  return h.toRadixString(16).padLeft(8, '0');
}

void main() {
  final scriptDir = p.dirname(Platform.script.toFilePath());
  final repoRoot = p.normalize(p.join(scriptDir, '..'));
  final stdSrc = p.join(repoRoot, 'micro-panda', 'std', 'src');
  final outFile = p.join(repoRoot, 'lib', 'src', 'stdlib_embedded.dart');

  final files = Directory(stdSrc)
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.mpd') && !f.path.endsWith('_test.mpd'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final entries = <({String key, String content})>[];
  for (final file in files) {
    final rel = p.withoutExtension(p.relative(file.path, from: stdSrc));
    final key = rel.replaceAll(p.separator, '.');
    final content = file.readAsStringSync();
    entries.add((key: key, content: content));
  }

  final hash = _computeHash(entries);

  final buf = StringBuffer();
  buf.writeln('// AUTO-GENERATED by tool/gen_stdlib.dart — do not edit manually.');
  buf.writeln('// Run: dart tool/gen_stdlib.dart');
  buf.writeln();
  buf.writeln('/// Hash of all embedded stdlib content. Used for fast staleness detection.');
  buf.writeln("/// Recomputed each time gen_stdlib.dart runs.");
  buf.writeln("const String kStdlibHash = '$hash';");
  buf.writeln();
  buf.writeln('/// Embedded standard library sources, keyed by module path.');
  buf.writeln("/// Excludes '*_test.mpd' files.");
  buf.writeln("/// Sub-directory modules use '.' as separator: 'hosted.memory'.");
  buf.writeln('const Map<String, String> kStdlib = {');

  for (final e in entries) {
    // Use a regular (non-raw) Dart string so ''' and """ inside .mpd files
    // don't terminate the embedding prematurely.
    final escaped = e.content
        .replaceAll(r'\', r'\\')
        .replaceAll(r'$', r'\$')
        .replaceAll('"""', r'\"\"\"');
    buf.writeln("  '${e.key}': \"\"\"$escaped\"\"\",");
  }

  buf.writeln('};');

  File(outFile).writeAsStringSync(buf.toString());
  print('Generated $outFile (hash: $hash, ${entries.length} modules: '
      '${entries.map((e) => e.key).join(', ')})');
}
