// Generates lib/src/stdlib_embedded.dart from micro-panda/std/src/**/*.mpd
// Run: dart tool/gen_stdlib.dart
import 'dart:io';
import 'package:path/path.dart' as p;

void main() {
  final scriptDir = p.dirname(Platform.script.toFilePath());
  final repoRoot = p.normalize(p.join(scriptDir, '..'));
  final stdSrc = p.join(repoRoot, 'micro-panda', 'std', 'src');
  final outFile = p.join(repoRoot, 'lib', 'src', 'stdlib_embedded.dart');

  final files = Directory(stdSrc)
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.mpd') && !f.path.endsWith('_test.mpd'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final buf = StringBuffer();
  buf.writeln('// AUTO-GENERATED by tool/gen_stdlib.dart — do not edit manually.');
  buf.writeln('// Run: dart tool/gen_stdlib.dart');
  buf.writeln();
  buf.writeln('/// Embedded standard library sources, keyed by module path.');
  buf.writeln("/// Excludes '*_test.mpd' files.");
  buf.writeln("/// Sub-directory modules use '.' as separator: 'hosted.memory'.");
  buf.writeln('const Map<String, String> kStdlib = {');

  for (final file in files) {
    // Key = relative path from stdSrc without extension, '/' → '.'
    // e.g. src/hosted/memory.mpd → 'hosted.memory'
    final rel = p.withoutExtension(p.relative(file.path, from: stdSrc));
    final key = rel.replaceAll(p.separator, '.');
    final content = file.readAsStringSync();
    buf.writeln("  '$key': r'''");
    buf.write(content);
    if (!content.endsWith('\n')) buf.writeln();
    buf.writeln("''',");
  }

  buf.writeln('};');

  File(outFile).writeAsStringSync(buf.toString());
  print('Generated $outFile (${files.length} modules: '
      '${files.map((f) {
        final rel = p.withoutExtension(p.relative(f.path, from: stdSrc));
        return rel.replaceAll(p.separator, '.');
      }).join(', ')})');
}
